### ISSUE TITLE
Images loading, Ping Errors

### ISSUE THREAD

**Issue by cashmire12** [furlongm/openvpn-monitor#42] opened 2017-04-07 21:59 UTC
Hey Guys, 

The python script was unable to load the images from the images folder (not sure why, they were also not directly available through the URL although permissions were correct).  I ended up moving the flags folder out of the images directory and to the /openvpn-monitor/  directory then changed line 651 to "output('<td><img src="/openvpn-monitor/{0!s}" title="{1!s}" alt="{1!s}" /> '.format(flag, full_location))" to resolve the issue.

Unfortunately the "last ping" will just return errors.  I've checked the networking and reach-ability to both the WAN, and Client cert ip's from both the Tap int, and the web-server, and they are reachable.  I can see from the logs, that the management interface  running version, state, status 3 , and quit commands, which I do not see yielding that information.

**Comment by kingy444** [comment] 2017-04-08 07:34
Images issue is fixed in pull request submitted but awaiting a cdnjs upload regarding some js files. This issue relates to the WebAlias config. Should be up in the next week or so hopefully

I have had no issues with the ping
Can you provide more info on your errors

**Comment by kingy444** [comment] 2017-04-08 07:37
If interested pull details are here https://github.com/furlongm/openvpn-monitor/pull/41

**Comment by furlongm** [comment] 2017-04-08 08:03
Sometimes the images are not displayed if a trailing slash is not used.

**Comment by furlongm** [comment] 2017-05-26 13:10
@cashmire12 can you check if adding a trailing slash to the URL helps your issue, or the pull request from @kingy444 helps?

I can't reproduce this issue, so will close it, but feel free to re-open.

**Closed by furlongm** 2017-05-26 13:10 UTC
