### ISSUE TITLE
Location section not showing flag logo and ping error

### ISSUE THREAD

**Issue by andrewglass3** [furlongm/openvpn-monitor#46] opened 2017-06-03 12:21 UTC
Hi there

Just installed and looks really cool.  However I have two issues:

1) Where it shows your location in the table its not giving me the flag icon 

2) Under ping I see only error yet the server this is hosted on can manually ping the remote client ips that are connected, does it try to ping the remote vpn ip?
![vpnmonitorerror](https://cloud.githubusercontent.com/assets/7479585/26753651/d4f27a3e-4862-11e7-871f-53f678aa2397.png)
 

Can you advise please?

Many thanks

Andy

**Comment by andrewglass3** [comment] 2017-06-04 07:25
Ive also noticed that it doesnt show the port in my example compared to your screenshots.

Cheers

Andy

**Comment by furlongm** [comment] 2017-07-21 19:50
@andrewglass3 can you add a trailing slash and see if that resolves the missing flags?

The port is deprecated and has been removed. Please see https://community.openvpn.net/openvpn/ticket/664 for further information.

**Comment by furlongm** [comment] 2017-07-21 20:03
For the ping error, can you send me the debug output from openvpn-monitor?

**Comment by Meisterschueler** [comment] 2017-08-31 20:34
I can confirm the missing flags. In an old installation (May 2016) the image points to "images/flags/xxx.png", in the current version the image points to "flags/xxx.png".

**Comment by furlongm** [comment] 2017-08-31 21:02
Can you add your O/S and how you have installed? Also, debug output from the CLI if possible.

**Comment by Meisterschueler** [comment] 2017-08-31 21:20
I am running an ubuntu instance on amazon ec2. The status bar from openvpn-monitor is:
OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
I installed it liked it is described on the main site of openvpn-monitor:
1. Install dependencies and configure apache for debian/ubuntu
2. Checkout OpenVPN-Monitor
3. Configure OpenVPN
4. Download the GeoLite City database
5. Configure OpenVPN-Monitor (I just deactivated the map and changed the names)

**Comment by Meisterschueler** [comment] 2017-08-31 21:21
`ubuntu@ip-172-31-44-112:/var/www/html/openvpn-monitor$ python openvpn-monitor.py -d
INFO: Using config file: ./openvpn-monitor.conf
DEBUG:
 === begin section
{u'datetime_format': '%d/%m/%Y %H:%M:%S', u'maps': 'False', u'site': 'OGN', u'geoip_data': '/usr/share/GeoIP/GeoIPCity.dat'}
=== end section
DEBUG:
 === begin section
{'host': 'localhost', 'show_disconnect': False, 'port': '5555', 'name': 'Wartungsnetzwerk II'}
=== end section
DEBUG:
 === begin raw data
OpenVPN Version: OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Management Version: 1
END

=== end raw data
DEBUG:
 === begin raw data
1504210218,CONNECTED,SUCCESS,10.9.0.1,
END

=== end raw data
DEBUG:
 === begin split line
[u'1504210218', u'CONNECTED', u'SUCCESS', u'10.9.0.1', u'']
=== end split line
DEBUG:
 === begin split line
[u'END']
=== end split line
DEBUG:
 === begin raw data
SUCCESS: nclients=1,bytesin=138980,bytesout=168708

=== end raw data
DEBUG:
 === begin split line
[u'nclients=1', u'bytesin=138980', u'bytesout=168708\r\n']
=== end split line
DEBUG:
 === begin raw data
TITLE	OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
TIME	Thu Aug 31 21:21:00 2017	1504214460
HEADER	CLIENT_LIST	Common Name	Real Address	Virtual Address	Bytes Received	Bytes Sent	Connected Since	Connected Since (time_t)	Username
CLIENT_LIST	Konstantin	92.211.143.241:61443	10.9.0.2	117680	132996	Thu Aug 31 20:11:26 2017	1504210286	UNDEF
HEADER	ROUTING_TABLE	Virtual Address	Common Name	Real Address	Last Ref	Last Ref (time_t)
ROUTING_TABLE	10.9.0.2	Konstantin	92.211.143.241:61443	Thu Aug 31 21:19:38 2017	1504214378
GLOBAL_STATS	Max bcast/mcast queue length	1
END

=== end raw data
DEBUG:
 === begin split line
deque([u'TITLE', u'OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017'])
=== end split line
DEBUG:
 === begin split line
deque([u'TIME', u'Thu Aug 31 21:21:00 2017', u'1504214460'])
=== end split line
DEBUG:
 === begin split line
deque([u'HEADER', u'CLIENT_LIST', u'Common Name', u'Real Address', u'Virtual Address', u'Bytes Received', u'Bytes Sent', u'Connected Since', u'Connected Since (time_t)', u'Username'])
=== end split line
DEBUG:
 === begin split line
deque([u'CLIENT_LIST', u'Konstantin', u'92.211.143.241:61443', u'10.9.0.2', u'117680', u'132996', u'Thu Aug 31 20:11:26 2017', u'1504210286', u'UNDEF'])
=== end split line
DEBUG:
 === begin split line
deque([u'HEADER', u'ROUTING_TABLE', u'Virtual Address', u'Common Name', u'Real Address', u'Last Ref', u'Last Ref (time_t)'])
=== end split line
DEBUG:
 === begin split line
deque([u'ROUTING_TABLE', u'10.9.0.2', u'Konstantin', u'92.211.143.241:61443', u'Thu Aug 31 21:19:38 2017', u'1504214378'])
=== end split line
DEBUG:
 === begin split line
deque([u'GLOBAL_STATS', u'Max bcast/mcast queue length', u'1'])
=== end split line
DEBUG:
 === begin split line
deque([u'END'])
=== end split line
DEBUG:
 === begin sessions
{'10.9.0.2': {u'bytes_recv': 117680,
              u'bytes_sent': 132996,
              u'city': u'Reckershausen',
              u'connected_since': datetime.datetime(2017, 8, 31, 20, 11, 26),
              u'country_name': 'Germany',
              u'last_seen': datetime.datetime(2017, 8, 31, 21, 19, 38),
              u'latitude': 49.983299255371094,
              u'local_ip': IPv4Address('10.9.0.2'),
              u'location': 'DE',
              u'longitude': 7.400000095367432,
              u'port': 61443,
              u'remote_ip': IPv4Address('92.211.143.241'),
              u'username': u'Konstantin'}}
=== end sessions
Content-Type: text/html

<!doctype html>
<html><head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OGN OpenVPN Status Monitor</title>
<meta http-equiv="refresh" content="300" />
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.4/css/theme.bootstrap.min.css" integrity="sha256-cerl+DYHeG2ZhV/9iueb8E+s7rubli1gsnKuMbKDvho=" crossorigin="anonymous" />
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.4/js/jquery.tablesorter.min.js" integrity="sha256-etMCBAdNUB2TBSMUe3GISzr+drx6+BjwAt9T3qjO2xk=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.4/js/jquery.tablesorter.widgets.min.js" integrity="sha256-29n48bNY/veiCp3sAG1xntm9MdMT5+IuZNpeJtV/xEg=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.4/js/parsers/parser-network.min.js" integrity="sha256-E0X65/rdWP806UYOzvOzTshT6a3R74j/9UOqcB9+6lc=" crossorigin="anonymous"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script>$(document).ready(function(){
$("table.tablesorter").tablesorter({theme:"bootstrap", headerTemplate:"{content} {icon}", widgets:["uitheme"]});
});</script>
</head><body>
<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" 
data-toggle="collapse" data-target="#myNavbar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">
OGN OpenVPN Status Monitor</a>
</div><div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav"><li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">VPN
<span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="#wartungsnetzwerk_ii">Wartungsnetzwerk II</a></li>
</ul></li>
</ul>
</div></div></nav>
<div class="container-fluid">
<div class="panel panel-success" id="wartungsnetzwerk_ii">
<div class="panel-heading"><h3 class="panel-title">Wartungsnetzwerk II</h3>
</div><div class="panel-body">
<table class="table table-condensed table-responsive">
<thead><tr><th>VPN Mode</th><th>Status</th><th>Pingable</th>
<th>Clients</th><th>Total Bytes In</th><th>Total Bytes Out</th>
<th>Up Since</th><th>Local IP Address</th>
</tr></thead><tbody>
<tr><td>Server</td>
<td>CONNECTED</td>
<td>Yes</td>
<td>1</td>
<td>138980 (135.7 KiB)</td>
<td>168708 (164.8 KiB)</td>
<td>31/08/2017 20:10:18</td>
<td>10.9.0.1</td>
</tr></tbody></table>
<table id="sessions" class="table table-striped table-bordered 
table-hover table-condensed table-responsive 
tablesorter tablesorter-bootstrap">
<thead><tr>
<th>Username / Hostname</th>
<th>VPN IP</th>
<th>Remote IP</th>
<th>Location</th>
<th>Bytes In</th>
<th>Bytes Out</th>
<th>Connected Since</th>
<th>Last Ping</th>
<th>Time Online</th>
</tr></thead><tbody>
<tr>
<td>Konstantin</td>
<td>10.9.0.2</td>
<td>92.211.143.241</td>
<td><img src="images/flags/de.png" title="Reckershausen, Germany" alt="Reckershausen, Germany" /> 
Reckershausen, Germany</td>
<td>117680 (114.9 KiB)</td>
<td>132996 (129.9 KiB)</td>
<td>31/08/2017 20:11:26</td>
<td>31/08/2017 21:19:38</td>
<td>1:09:34</td>
</tr>
</tbody></table>
<span class="label label-default">OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017</span>
</div></div>
DEBUG:
 === begin vpns
{'VPN1': {'host': 'localhost',
          'name': 'Wartungsnetzwerk II',
          'port': '5555',
          u'semver': Version('2.3.10'),
          u'sessions': {'10.9.0.2': {u'bytes_recv': 117680,
                                     u'bytes_sent': 132996,
                                     u'city': u'Reckershausen',
                                     u'connected_since': datetime.datetime(2017, 8, 31, 20, 11, 26),
                                     u'country_name': 'Germany',
                                     u'last_seen': datetime.datetime(2017, 8, 31, 21, 19, 38),
                                     u'latitude': 49.983299255371094,
                                     u'local_ip': IPv4Address('10.9.0.2'),
                                     u'location': 'DE',
                                     u'longitude': 7.400000095367432,
                                     u'port': 61443,
                                     u'remote_ip': IPv4Address('92.211.143.241'),
                                     u'username': u'Konstantin'}},
          'show_disconnect': False,
          u'socket_connected': True,
          u'state': {u'connected': u'CONNECTED',
                     u'local_ip': IPv4Address('10.9.0.1'),
                     u'mode': u'Server',
                     u'remote_ip': u'',
                     u'success': u'SUCCESS',
                     u'up_since': datetime.datetime(2017, 8, 31, 20, 10, 18)},
          u'stats': {u'bytesin': 138980, u'bytesout': 168708, u'nclients': 1},
          u'version': u'OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017'}}
=== end vpns`

**Comment by furlongm** [comment] 2017-09-20 04:19
@andrewglass3 do you still have an issue or did it work in the end?
@Meisterschueler can you try with a newer version of openvpn? e.g. using 

```
deb http://build.openvpn.net/debian/openvpn/release/2.4 xenial main
```

**Comment by Meisterschueler** [comment] 2017-09-20 06:17
@furlongm I just made a system update (apt-get update + upgrade), and the openvpn version remains 2.3.10, so this version seems to be the default version of ubuntu. I want to keep my system "default ubuntu" ...
For me the problem seems not a openvpn problem since just the country image path is corrupt. See my comment here: https://github.com/furlongm/openvpn-monitor/issues/46#issuecomment-326413117

**Comment by Meisterschueler** [comment] 2017-11-03 13:22
I set up a new server with openvpn 2.4. The problem is still the same. So I compared the html in the browser with the html generated with "python openvpn-monitor.py. We have following difference:
in the browser: `<img src="flags/de.png" title="Munich, Germany" alt="Munich, Germany" />`
in the generated: `<img src="images/flags/de.png" title="Munich, Germany" alt="Munich, Germany" />`

**Comment by furlongm** [comment] 2017-11-03 13:50
Hi, can you post a screenshot incluing the url bar?

**Comment by Meisterschueler** [comment] 2017-11-03 13:58
![image](https://user-images.githubusercontent.com/4268343/32377289-6b483e58-c0a7-11e7-8fe3-55acb2ab52aa.png)

**Comment by furlongm** [comment] 2017-11-03 14:05
Can you try putting a trailing slash on the url? e.g. openvpn-monitor/

**Comment by Meisterschueler** [comment] 2017-11-03 14:10
Aaaaa! That works! I think the behaviour should be independet from trailing slash...

**Comment by Meisterschueler** [comment] 2017-11-03 14:14
I have a server with commit 'a03ee44': here I am redirected from "no trailing slash" to "trailing slash", with the current version this do not work.

**Comment by furlongm** [comment] 2017-11-03 14:16
Redirection is typically handled by e.g. apache. Bottle doesn't handle this.

**Comment by furlongm** [comment] 2017-11-30 03:39
Closing due to workaround and updated documentation. Trailing slash should be handled by redirection of web server.

**Closed by furlongm** 2017-11-30 03:39 UTC

**Comment by toxanes** [comment] 2019-05-29 14:59
Hi,
I have a problem 
LAST PING: ERROR
I use dev tap
How do I fix the problem?

**Comment by Jafar412** [comment] 2021-08-14 23:21
For anyone wants  to rewrite the trailing slash , just add in apache 
RewriteRule ^/openvpn-monitor$ https://%{HTTP_HOST}/openvpn-monitor/ [L,R=301]

**Comment by Pljushevij** [comment] 2022-03-15 11:26
Hello. I also have problem with country flag logo.
My OpenVPN Monitor works in this case:
http://vpn_server_ip
Installation instruction:
https://blog.dftorres.ca/?p=348

What wrong?
