### ISSUE TITLE
Location repeated twice in vpn client/host list

### ISSUE THREAD

**Issue by elapse2039** [furlongm/openvpn-monitor#26] opened 2017-01-03 14:58 UTC
![virtualbox_mint_03_01_2017_09_54_29](https://cloud.githubusercontent.com/assets/5325698/21611499/0d7539c6-d19b-11e6-89d7-5a7ab8cdd4d5.png)

Location specifies the name twice, no flag shown. (Remote IP address removed from screenshot - it is working)

**Comment by furlongm** [comment] 2017-01-03 23:47
Can you inspect element to show the html for that <td>?

Or run from the command line with `python openvpn-monitor.py -d` to get the html?

Thanks.

**Comment by furlongm** [comment] 2017-01-05 11:54
Is it possible you are missing a trailing slash on your URL?

**Comment by furlongm** [comment] 2017-01-12 06:43
I think this issue was caused by a missing trailing slash so I'm going to close it. Feel free to reopen if it still occurs after adding the trailing slash.

**Closed by furlongm** 2017-01-12 06:43 UTC
Labels: bug
